apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cryptox.fullname" . }}
  labels:
    app: {{ include "cryptox.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cryptox.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cryptox.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: {{ .Values.env.DATABASE_URL }}
        - name: REDIS_URL
          value: {{ .Values.env.REDIS_URL }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
